### ISSUE TITLE
Please consider using a more comprehensive `.gitignore`

### ISSUE THREAD

**Issue by unilock** [Qzimyion/TintedPotions#2]
Most projects don't include runtime files (`/.idea`, `/**/run`, etc.) in their git repositories; they bloat the commit history and make clones take longer.

You can exclude them with `.gitignore`. For example, this is the one I use with my Architectury Loom projects:  
https://github.com/unilock/deslabification/blob/cf9801b298ebf3d0e572f800564bd192a97d665b/.gitignore

**Comment by Qzimyion** [comment]
Alright
